### ISSUE TITLE
On ENTER press, the form is sent and the page is refreshed

### ISSUE THREAD

**Issue by nitodico** [VoIPstudio/webphone-demo#2]
When pressing ENTER on the phone input the data is sent, and the page refreshed so you have to confirm again the microphone access if isn't server in a HTTPS enviroment

It can be fixed in this way changing the form tag like this

```html
<form class="row g-2" onsubmit="document.querySelector('#call').click();return false">
```

Not the most proper way to do it but it works

**Comment by amuzacz** [comment]
Basically we want to stay on the page, fixed b7aebf0

Thanks.
